title: Arshu Hansda # your name (or website title) here
logo: "/images1/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of development and Consultant experience. Possess Bachelor's Degree in Information Technology from Birla Institute of Technology in Mersa, Ranchi.
  <br><br>
  Currently in Capgemini India serving as Automation Developer. I'm on the Asia Pacific Team, working with customers from South America and Korea Team in the Consumer Products Distribution Market. Hands on experience in automating business process with Blueprism and data analysis with python and SQL to solve challenging business problems with data driven decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/arshuhansda/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
